blog_phoenix/web/router.ex
defmodule BlogPhoenix.Router do
  use BlogPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/blog", BlogController, :index
    get "/login", LoginController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogPhoenix do
  #   pipe_through :api
  # end
end

blog_phoenix/lib/blog_phoenix/endpoint.ex
defmodule BlogPhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :blog_phoenix

  socket "/socket", BlogPhoenix.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blog_phoenix, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_blog_phoenix_key",
    signing_salt: "skzmd+At"

  plug BlogPhoenix.Router
end

blog_phoenix/lib/blog_phoenix/repo.ex
defmodule BlogPhoenix.Repo do
  use Ecto.Repo, otp_app: :blog_phoenix
end

blog_phoenix/web/controllers/blog_controller.ex
defmodule BlogPhoenix.BlogController do
  use BlogPhoenix.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

blog_phoenix/web/controllers/login_controller.ex
defmodule BlogPhoenix.LoginController do
  use BlogPhoenix.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

blog_phoenix/web/controllers/page_controller.ex
defmodule BlogPhoenix.PageController do
  use BlogPhoenix.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

blog_phoenix/web/views/blog_view.ex
defmodule BlogPhoenix.BlogView do
  use BlogPhoenix.Web, :view
end

blog_phoenix/web/views/error_view.ex
defmodule BlogPhoenix.ErrorView do
  use BlogPhoenix.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

blog_phoenix/web/views/layout_view.ex
defmodule BlogPhoenix.LayoutView do
  use BlogPhoenix.Web, :view
end

blog_phoenix/web/views/login_view.ex
defmodule BlogPhoenix.LoginView do
  use BlogPhoenix.Web, :view
end

blog_phoenix/web/views/page_view.ex
defmodule BlogPhoenix.PageView do
  use BlogPhoenix.Web, :view
end

blog_phoenix/web/templates/blog/index.html.eex
<div class="jumbotron">
    <h2>New Blog Entry</h2>
</div>

blog_phoenix/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Phoenix Framework Blog</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>
      $(document).ready(function(){alert('hi');});
    </script> 
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">Phoenix Blog</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="<%= page_path(@conn, :index) %>">Home <span class="sr-only">(current)</span></a></li>
                <li><a href="<%= blog_path(@conn, :index) %>">New Blog</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <div class="btn-group">
                    <button type="button" class="btn btn-default navbar-btn" onclick="window.location.href='<%= login_path(@conn, :index) %>'">Sign in</button>
                  </div>
                </li>
              </ul>
            </div>
        </div>
        </nav>
      </header>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

blog_phoenix/web/templates/login/index.html.eex
<div class="jumbotron">
    <h2>Login Page</h2>
</div>

blog_phoenix/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix Blog!" %></h2>
  <p class="lead">Blogging software created with Phoenix Framework, PostgreSQL, Brunch, Bootstrap and more!</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
  <div>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
    <p>spacing</p>
  </div>
</div>